/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellIndexRouteImport } from './routes/sell.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as ListingsNewRouteImport } from './routes/listings.new'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as SellListYourOwnRouteImport } from './routes/sell.list-your-own'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as ListingsIdEditRouteImport } from './routes/listings.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
// Layout route — sell.tsx renders <Nav/> + <Outlet/> for its children below.
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
// Layout route — agents.tsx renders <Nav/> + <Outlet/> for its children below.
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsNewRoute = ListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const SellListYourOwnRoute = SellListYourOwnRouteImport.update({
  id: '/list-your-own',
  path: '/list-your-own',
  getParentRoute: () => SellRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const ListingsIdEditRoute = ListingsIdEditRouteImport.update({
  id: '/listings/$id/edit',
  path: '/listings/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agents/$id': typeof AgentsIdRoute
  '/sell/list-your-own': typeof SellListYourOwnRoute
  '/agents/': typeof AgentsIndexRoute
  '/listings/new': typeof ListingsNewRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/sell/': typeof SellIndexRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agents/$id': typeof AgentsIdRoute
  '/sell/list-your-own': typeof SellListYourOwnRoute
  '/agents': typeof AgentsIndexRoute
  '/listings/new': typeof ListingsNewRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/sell': typeof SellIndexRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agents/$id': typeof AgentsIdRoute
  '/sell/list-your-own': typeof SellListYourOwnRoute
  '/agents/': typeof AgentsIndexRoute
  '/listings/new': typeof ListingsNewRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/sell/': typeof SellIndexRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/apply'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/profile'
    | '/sell'
    | '/sitemap.xml'
    | '/agents/$id'
    | '/sell/list-your-own'
    | '/agents/'
    | '/listings/new'
    | '/properties/$id'
    | '/sell/'
    | '/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/profile'
    | '/sitemap.xml'
    | '/agents/$id'
    | '/sell/list-your-own'
    | '/agents'
    | '/listings/new'
    | '/properties/$id'
    | '/sell'
    | '/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/apply'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/profile'
    | '/sell'
    | '/sitemap.xml'
    | '/agents/$id'
    | '/sell/list-your-own'
    | '/agents/'
    | '/listings/new'
    | '/properties/$id'
    | '/sell/'
    | '/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  SellRoute: typeof SellRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ListingsNewRoute: typeof ListingsNewRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  ListingsIdEditRoute: typeof ListingsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof SellRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/new': {
      id: '/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof ListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/sell/list-your-own': {
      id: '/sell/list-your-own'
      path: '/list-your-own'
      fullPath: '/sell/list-your-own'
      preLoaderRoute: typeof SellListYourOwnRouteImport
      parentRoute: typeof SellRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/listings/$id/edit': {
      id: '/listings/$id/edit'
      path: '/listings/$id/edit'
      fullPath: '/listings/$id/edit'
      preLoaderRoute: typeof ListingsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface SellRouteChildren {
  SellListYourOwnRoute: typeof SellListYourOwnRoute
  SellIndexRoute: typeof SellIndexRoute
}

const SellRouteChildren: SellRouteChildren = {
  SellListYourOwnRoute: SellListYourOwnRoute,
  SellIndexRoute: SellIndexRoute,
}

const SellRouteWithChildren = SellRoute._addFileChildren(SellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  SellRoute: SellRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ListingsNewRoute: ListingsNewRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  ListingsIdEditRoute: ListingsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
