/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as ListingsNewRouteImport } from './routes/listings.new'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as ListingsIdEditRouteImport } from './routes/listings.$id.edit'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsNewRoute = ListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const ListingsIdEditRoute = ListingsIdEditRouteImport.update({
  id: '/listings/$id/edit',
  path: '/listings/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/updates': typeof UpdatesRoute
  '/agents/$id': typeof AgentsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/updates': typeof UpdatesRoute
  '/agents/$id': typeof AgentsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/updates': typeof UpdatesRoute
  '/agents/$id': typeof AgentsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/sitemap.xml'
    | '/updates'
    | '/agents/$id'
    | '/listings/new'
    | '/properties/$id'
    | '/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/sitemap.xml'
    | '/updates'
    | '/agents/$id'
    | '/listings/new'
    | '/properties/$id'
    | '/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/sitemap.xml'
    | '/updates'
    | '/agents/$id'
    | '/listings/new'
    | '/properties/$id'
    | '/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UpdatesRoute: typeof UpdatesRoute
  ListingsNewRoute: typeof ListingsNewRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  ListingsIdEditRoute: typeof ListingsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/new': {
      id: '/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof ListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/listings/$id/edit': {
      id: '/listings/$id/edit'
      path: '/listings/$id/edit'
      fullPath: '/listings/$id/edit'
      preLoaderRoute: typeof ListingsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UpdatesRoute: UpdatesRoute,
  ListingsNewRoute: ListingsNewRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  ListingsIdEditRoute: ListingsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
